### PR TITLE
Cart - Fully loaded with PayPal integration

### LINKED ISSUE #1: Integrate Paypal Express Checkout

### LINKED ISSUE #2: Add shopping cart page

### LINKED ISSUE #4: "My Cart" Button
There should be a button in the top right for "My Cart"

### PR DESCRIPTION
**Pull request by julianpoy**
This fully loads the cart (pun intended) with PayPal integration, and better promise use.

All ready to go.

Closes #4 
Closes #1 
Closes #2

### CODE REVIEW

**Comment by julianpoy** [comment]
@torch2424 I believe this works and no bugs were introduced, however could you test? All you have to do is poke around on http://dev.kondeo.com/skincareshop/
If there are any bugs, let me know.

**Comment by torch2424** [comment]
@julianpoy is it alright If i test on wednesday or is this priority?

**Comment by julianpoy** [comment]
Wednesday is fine. Not really an intense check, just want you to poke around and try stuff that I might not have.

**Comment by julianpoy** [comment]
I cant wait for you any longer to pull this in, unfortunately. I'll have to pull this in myself.

**Pull request merged**
